/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fbxchecker_NativeJavaCpp */

#ifndef _Included_com_example_fbxchecker_NativeJavaCpp
#define _Included_com_example_fbxchecker_NativeJavaCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fbxchecker_NativeJavaCpp
 * Method:    fbxParseJson
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fbxchecker_NativeJavaCpp_fbxParseJson
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
